# Generated by Django 5.1.7 on 2025-04-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortenedurl_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='shortened_url',
            field=models.URLField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.URLField(max_length=100000),
        ),
    ]
